// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/model.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "gophkeeper/internal/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, username, password string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, username, password)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, username, password)
}

// CreateVault mocks base method.
func (m *MockRepository) CreateVault(ctx context.Context, uv model.UserVault) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVault", ctx, uv)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVault indicates an expected call of CreateVault.
func (mr *MockRepositoryMockRecorder) CreateVault(ctx, uv interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVault", reflect.TypeOf((*MockRepository)(nil).CreateVault), ctx, uv)
}

// DeleteVault mocks base method.
func (m *MockRepository) DeleteVault(ctx context.Context, ID, userID int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVault", ctx, ID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVault indicates an expected call of DeleteVault.
func (mr *MockRepositoryMockRecorder) DeleteVault(ctx, ID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVault", reflect.TypeOf((*MockRepository)(nil).DeleteVault), ctx, ID, userID)
}

// GetVault mocks base method.
func (m *MockRepository) GetVault(ctx context.Context, ID, userID int32) (model.UserVault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVault", ctx, ID, userID)
	ret0, _ := ret[0].(model.UserVault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVault indicates an expected call of GetVault.
func (mr *MockRepositoryMockRecorder) GetVault(ctx, ID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVault", reflect.TypeOf((*MockRepository)(nil).GetVault), ctx, ID, userID)
}

// ListVaults mocks base method.
func (m *MockRepository) ListVaults(ctx context.Context, userID int32) ([]model.UserVault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVaults", ctx, userID)
	ret0, _ := ret[0].([]model.UserVault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVaults indicates an expected call of ListVaults.
func (mr *MockRepositoryMockRecorder) ListVaults(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVaults", reflect.TypeOf((*MockRepository)(nil).ListVaults), ctx, userID)
}

// LoginUser mocks base method.
func (m *MockRepository) LoginUser(ctx context.Context, username string) (int32, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", ctx, username)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockRepositoryMockRecorder) LoginUser(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockRepository)(nil).LoginUser), ctx, username)
}

// Ping mocks base method.
func (m *MockRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockRepositoryMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockRepository)(nil).Ping), ctx)
}
